version: "2.4"
# This server profile used as basis for ping-devop docker-launch

#-------------------------------------------------------------------------------------
#- Ping Identity PingAccess getting started demo
#-
#-                +---------------+
#-                |   PingAccess  |
#-                +---------------+
#-
#- To access PingAccess Console
#-
#-    https://localhost:9000/
#-
#-    Username: administrator
#-    Password: 2FederateM0re
#-------------------------------------------------------------------------------------

services:
  pingaccess:
    image: ${PING_IDENTITY_DEVOPS_REGISTRY}/pingaccess:${PING_IDENTITY_DEVOPS_TAG}
    env_file:
      - ${HOME}/.pingidentity/devops
    ports:
      - "3000:3000"
      - "9000:9000"
    networks:
      - pingnet
    volumes:
      - ${HOME}/projects/devops/pingidentity-server-profiles/getting-started/pingaccess:/opt/in

networks:
  pingnet:


